Update master to 1.1.2
Nanostring-Biostats/GeomxTools pull request #106
Opened 2021-08-25 22:58 UTC by NicoleEO

Includes DE, bug fixes, and documentation updates

2021-08-28 00:27 UTC, NicoleEO commented
@rvitancol this includes review of all these commits https://github.com/Nanostring-Biostats/GeomxTools/compare/8b9db0aa382c3829189c4b391655d0926d420ce0...dev

2021-09-02 17:08 UTC, rvitancol requested changes

2021-09-02 21:23 UTC, NicoleEO commented on tests/testthat/test_GeoMxSet_probeCollapse.R
> +})
We will add these in a separate PR. @maddygriz is working on this issue now where I logged the above. https://github.com/Nanostring-Biostats/GeomxTools/issues/107

2021-09-02 22:00 UTC, NicoleEO commented on R/NanoStringGeoMxSet-aggregate.R
> +
Fixed

2021-09-02 22:00 UTC, NicoleEO commented on R/NanoStringGeoMxSet-aggregate.R
> +
Fixed

2021-09-08 16:42 UTC, rvitancol approved these changes

2021-09-08 17:32 UTC, merged