Seurat and SpatialExperiment integration
Nanostring-Biostats/GeomxTools pull request #139
Opened 2021-11-24 18:46 UTC by maddygriz

counts, metadata, and coordinates are integrated. Images will take more thought and will come after image package

2021-12-07 21:54 UTC, NicoleEO requested changes
Can you increment the version and update news? I would like to make sure we increment every version a user can potentially pull even if from dev.
Please add test cases, update reqs and specs in qb as well so we can run test case before merge. Only need to include for the piece written so far.

2021-12-07 21:54 UTC, NicoleEO commented on R/convertors.R
> +to.Seurat <- function(object, ident, normData = "exprs_norm", coordinates = NULL, forceRaw = FALSE){
objects are not guaranteed to have "exprs_norm". I would either default to "exprs" or set to NULL. If NULL add check.

2021-12-07 21:54 UTC, NicoleEO commented on R/convertors.R
> +
Can you add a check for the assay data name existing?

2021-12-07 21:54 UTC, NicoleEO commented on R/convertors.R
> +to.SpatialExperiment <- function(object, normData = "exprs_norm", coordinates = NULL, forceRaw = FALSE){
Same here, either default to "exprs" or set to NULL. If NULL add check.

2021-12-07 21:54 UTC, NicoleEO commented on R/convertors.R
> +
Add check for assay data name being present.

2021-12-08 17:19 UTC, NicoleEO commented
Can you also add update the authors in the description to match the readme?

2021-12-10 17:18 UTC, NicoleEO requested changes
A few minor edits. And I am also getting the following errors in the test.
![image](https://user-images.githubusercontent.com/20404635/145614900-f97b9cc1-f16d-4b45-aa6f-3a8b59ac6416.png)

2022-01-27 22:44 UTC, NicoleEO requested changes

2022-01-28 18:57 UTC, maddygriz commented on R/coercions.R
> +    seuratConvert@misc[["QCMetrics"]] <- sData(object)[colnames(sData(object)) %in% QCMetrics]
The empty dataframe is now NULL. Tests have been updated. same for SpatialExperiment

2022-01-28 18:58 UTC, maddygriz commented
Changes have all been added. Working on creating issues

2022-01-28 21:38 UTC, NicoleEO approved these changes
looks great

2022-02-04 00:36 UTC, merged