Protein integration
Nanostring-Biostats/GeomxTools pull request #142
Opened 2022-02-04 00:40 UTC by maddygriz

Data containing different analytes can be separated and protein data has extra QC steps added. Protein data can go through HK and Neg normalization. 
Added functionality for ignoring PKC files that weren't actually used in the study compared to the config file. 
Tests have been added for all new features. I did not rewrite tests to validate outputs when using protein instead of RNA. I only wrote tests for the new features.

2022-02-07 22:05 UTC, NicoleEO requested changes
I haven't fully reviewed yet, but wanted to stop here as after some testing I realized there are some nuances to implementing this way. Particularly several functions, you would need to subset by analyte type and this starts at segment QC, which is the first step of analysis. Given that, I would like to propose changing this implementation.

1. Always split the data from the get go, do not wait until normalization. When load ask if they want to generate the prot or RNA version of the class. 
2. Add analyte type as part of experiment data instead of fData since it applies to the whole object just like featureType. It should also have a corresponding get and replace function like featureType
3. For those functions that are RNA only check for RNA before proceeding and the same for protein

2022-02-07 22:05 UTC, NicoleEO commented on R/NanoStringGeoMxSet-qc.R
> +concordance_plot <- function(mat, col = rgb(0, 0, 0, 0.5),
Plots should go in autoplot. Check out nctools for similar implementation.

2022-02-10 20:24 UTC, NicoleEO requested changes

2022-02-10 20:52 UTC, NicoleEO commented on R/NanoStringGeoMxSet-class.R
>                                NanoStringGeoMxSet = "2.0.0")),
Let's also bump this version

2022-02-10 20:53 UTC, NicoleEO commented on DESCRIPTION
>               person("Zhi", "Yang", email = "zyang@nanostring.com", role = c("aut")))
Bump version here too. I think you may need to pull in current dev first.

2022-02-11 22:21 UTC, maddygriz commented on inst/extdata/DSP_Proteogenomics_Example_Data/Hs_P_NGS_ADPath_Ext_v1.0.pkc
> +{
rewrote tests to pull from zip folder instead of individual file

2022-02-11 22:22 UTC, maddygriz commented on tests/testthat/test_GeoMxSet_accessors.R
> +proteinData <- readRDS(file= system.file("extdata","DSP_Proteogenomics_Example_Data",
yes

2022-02-11 22:30 UTC, maddygriz commented on R/NanoStringGeoMxSet-autoplot.R
> +  negfactor <- apply(raw[neg.names, , drop = FALSE], 2, function(x){pmax(ngeoMean(x), 1)})
I asked Alyssa and she said it should be geomean rather than just average. so maybe a bug in the plugin?

2022-02-11 22:38 UTC, maddygriz commented on R/NanoStringGeoMxSet-normalize.R
> +  if (any(colnames(segmentAnnotations) == area)) {
any(colnames(segmentAnnotations) == NULL) is false and the statement is skipped
shown in test_protein.R lines 165-172

2022-02-11 22:38 UTC, maddygriz commented on R/NanoStringGeoMxSet-normalize.R
> +  if (any(colnames(segmentAnnotations) == nuclei)) {
any(colnames(segmentAnnotations) == NULL) is false and the statement is skipped
shown in test_protein.R lines 165-172

2022-02-11 22:43 UTC, maddygriz commented on R/readNanoStringGeoMxSet.R
> +    # pkcHeader[["PKCFileDate"]] <- as.character(pkcHeader[["PKCFileDate"]])
ensuring the PKCFileDate was a character only removed the names of the previous character vector 
![image](https://user-images.githubusercontent.com/40255151/153680581-0064707b-afa9-4f4b-b5a0-4dcd4a374f57.png)
I was using the names to subset based on analyte, but it might be fine to not comment out now that we are only reading in the correct analyte instead of subsetting.

2022-02-11 22:52 UTC, maddygriz commented on R/readNanoStringGeoMxSet.R
> +
If we want to do that, we should probably call aggregateCounts automatically instead of just setting featureType so that all of the extra stuff, like changing rownames to targets, is done as well.

2022-02-11 22:53 UTC, maddygriz commented on tests/testthat/test_protein.R
> +proteinData <- suppressWarnings(aggregateCounts(proteinData))
yes we need the capability of changing rownames to target names instead of probeIDs

2022-02-11 22:56 UTC, maddygriz commented on tests/testthat/test_protein.R
> +  expect_warning(expect_warning(expect_warning(setBioProbeQCFlags(proteinData,
yes there are 3 separate warnings and strangely you get an error with expect_warning if there are multiple 
![image](https://user-images.githubusercontent.com/40255151/153681808-898c4913-5306-439b-ad88-3e75681af6a5.png)

2022-02-11 23:26 UTC, maddygriz commented on R/readNanoStringGeoMxSet.R
> +    extraPKCs <- unique(pkcProbes$Module[which(!pkcProbes$RTS_ID %in% targets)])
This is comparing the pkc & the config so there shouldn't be any missing targets as they are both "truth" documents. So if there is one discrepancy, I assumed the entire pkc was added mistakenly. If there was a version difference between config and given pkc, there would be a warning removing the pkc in this step and an error downstream with missing pkc files. I can add an extra check in this function for potential versioning issues

2022-02-11 23:47 UTC, maddygriz commented on R/NanoStringGeoMxSet-autoplot.R
> +qcProteinSignal <- function(object, neg.names=NULL) {
I can definitely split it but by saving the plot do you mean in a data file or as a plot? couldn't you save this plot even with the order variable being returned using `png(...) proteinOrder <- qcProteinSignal(...) dev.off()`?

2022-02-12 00:02 UTC, NicoleEO commented on R/readNanoStringGeoMxSet.R
> +
Good point. Yes, I think if we call aggCounts in the read function it would look better. That way this is extrapolated from the user having to do, but maybe ask Alyssa to see what's most natural. Are the users used to initially just looking at everything with Target names already associated?

2022-02-12 00:06 UTC, NicoleEO commented on R/readNanoStringGeoMxSet.R
> +    extraPKCs <- unique(pkcProbes$Module[which(!pkcProbes$RTS_ID %in% targets)])
Let's add an extra check like the length of missing probes from a module == length of probes in module pkc. I can only guess that with revisioning coming up we'll see some funky asks.

2022-02-12 00:07 UTC, NicoleEO commented on R/NanoStringGeoMxSet-autoplot.R
> +qcProteinSignal <- function(object, neg.names=NULL) {
The main advantage of passing back the plot is someone could edit it more after running our function. Example in 360s we'll call autoplot to plot a boxplot. Used the return generic plot from the autoplot function and add additional lines etc to the plot to customize further.

2022-02-12 00:10 UTC, maddygriz commented on R/NanoStringGeoMxSet-autoplot.R
> +qcProteinSignal <- function(object, neg.names=NULL) {
so we should probably return every plot, not just this one.

2022-02-12 00:12 UTC, maddygriz commented on R/readNanoStringGeoMxSet.R
> +    # pkcHeader[["PKCFileDate"]] <- as.character(pkcHeader[["PKCFileDate"]])
I probably should have noted that when the names are removed, this is the only metadata item that doesn't have the pkc name attached to it. So when there are multiple pkcs you don't know which date goes with which pkc. Technically they are all in the same order but you never know if they might change for some reason.

2022-02-12 00:12 UTC, NicoleEO commented on R/NanoStringGeoMxSet-autoplot.R
> +qcProteinSignal <- function(object, neg.names=NULL) {
Yes, that's ideal

2022-02-12 00:36 UTC, maddygriz commented on R/readNanoStringGeoMxSet.R
> +    # pkcHeader[["PKCFileDate"]] <- as.character(pkcHeader[["PKCFileDate"]])
Ya if we leave it commented out it fixes this issue.

2022-02-15 18:16 UTC, NicoleEO requested changes
Minor things left. Can you also address the items below associated with your updates? You can ignore the notes that are associated with old code stuff like the targetnames binding.

* using log directory ‘/home/rstudio/GeomxTools.Rcheck’
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘GeomxTools/DESCRIPTION’ ... OK
* this is package ‘GeomxTools’ version ‘2.1.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘GeomxTools’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 22.9Mb
  sub-directories of 1Mb or more:
    doc       3.6Mb
    extdata  18.4Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
aggregateCounts: no visible binding for global variable ‘TargetName’
hkNorm: no visible binding for global variable ‘TargetName’
mixedModelDE: multiple local function definitions for ‘deFunc’ with
  different formal arguments
setGrubbsFlags: no visible binding for global variable ‘TargetName’
setGrubbsFlags : <anonymous>: no visible binding for global variable
  ‘Module’
setProbeRatioFlags: no visible binding for global variable ‘TargetName’
setTargetFlags: no visible global function definition for ‘analtye’
subtractBackground : <anonymous>: no visible binding for global
  variable ‘Module’
to.Seurat: no visible global function definition for ‘new’
setSignatureFuncs<-,NanoStringGeoMxSet-character: no visible global
  function definition for ‘setSigFuncs<-’
signatureScores,NanoStringGeoMxSet: no visible global function
  definition for ‘assayDataElement2’
signatureScores,NanoStringGeoMxSet: no visible global function
  definition for ‘.sigCalc’
Undefined global functions or variables:
  .sigCalc analtye assayDataElement2 Module new setSigFuncs<-
  TargetName
Consider adding
  importFrom("methods", "new")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'normalize,NanoStringGeoMxSet-method':
  ‘byPanel’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... NOTE
Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/GeomxSet_coercions.Rmd’
(Is a VignetteBuilder field missing?)
* checking examples ... ERROR
Running examples in ‘GeomxTools-Ex.R’ failed
The error most likely occurred in:

> ### Name: concordancePlot
> ### Title: Produce concordance pairs plots
> ### Aliases: concordancePlot
> 
> ### ** Examples
> 
> # simulate HKs:
> x = pmax(rnorm(100, 50, 10), 0)
> mat = sweep(matrix(rnorm(300, 0, 5), 100), 1, x, "+")
> concordancePlot(mat = mat, col = rep(c("blue", "orange"), each = 50))
Error in concordancePlot(mat = mat, col = rep(c("blue", "orange"), each = 50)) : 
  could not find function "concordancePlot"
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  The following object is masked from 'package:base':
  
      print.default
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test_protein.R:46:3): Datasets can be subset by given analyte ──────
  featureType(RNAData) == "Probe" is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 266 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘Developer_Introduction_to_the_NanoStringGeoMxSet.Rmd’ using ‘UTF-8’... OK
  ‘Protein_in_GeomxTools.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Warning in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  texi2dvi script/program not available, using emulation
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Warning in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  texi2dvi script/program not available, using emulation
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -Rf /tmp/Rtmp94pPdY/Rd2pdf565d6122573d'
* DONE

Status: 3 ERRORs, 2 WARNINGs, 5 NOTEs
See
  ‘/home/rstudio/GeomxTools.Rcheck/00check.log’
for details.

2022-02-16 18:31 UTC, maddygriz commented on R/NanoStringGeoMxSet-autoplot.R
> +qcProteinSignalNames <- function(object, neg.names){
I was trying to come up with a way to not repeat code but for some reason I couldn't think of this simple solution. Thanks

2022-02-16 18:32 UTC, maddygriz commented on vignettes/Protein_in_GeomxTools.Rmd
> +rect(xleft = 3.5, xright = tyrosineHydroxylase, ybottom = -6, ytop = 10, density = 2, col = "red", lty = 3)
That is what happens when you return the image. Thanks for suggesting it.

2022-02-16 21:36 UTC, NicoleEO approved these changes

2022-04-01 21:31 UTC, maddygriz commented
Approved by Shilah

2022-04-07 21:16 UTC, NicoleEO requested changes
Can you also run the build check and put results in PR?

2022-04-07 21:16 UTC, NicoleEO commented on R/NanoStringGeoMxSet-autoplot.R
> +    print.sd.log.ratio <- function(data, mapping) {
Since you're editing anyways, can we move this out of function within function?

2022-04-07 21:16 UTC, NicoleEO commented on vignettes/Protein_in_GeomxTools.Rmd
> +```{r, fig.width= 12, fig.height=7, eval=FALSE}
Is eval = FALSE correct? You don't want the user to run this at all without updating the markdown to eval=TRUE

2022-04-07 21:25 UTC, maddygriz commented on vignettes/Protein_in_GeomxTools.Rmd
> +```{r, fig.width= 12, fig.height=7, eval=FALSE}
yes Prajan said that filtering proteins doesn't really happen in the field but wants people to know how to do it if they want to. So both filtering code chunks are eval = FALSE

2022-04-08 22:05 UTC, maddygriz commented
check looks good. The mixedModelDE example always fails on my instance. 

── R CMD check results ────────────────────────────────────────────────────────────────────────────────────────────────────── GeomxTools 2.1.2 ────
Duration: 14m 18.7s

> checking examples ... ERROR
  Running examples in ‘GeomxTools-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: mixedModelDE
  > ### Title: Run a mixed model on GeoMxSet
  > ### Aliases: mixedModelDE
  > 
  > ### ** Examples
  > 
  > datadir <- system.file("extdata", "DSP_NGS_Example_Data", package = "GeomxTools")
  > demoData <- readRDS(file.path(datadir, "/demoData.rds"))
  > target_demoData <- aggregateCounts(demoData)
  > target_demoData <- normalize(target_demoData, norm_method="quant")
  > target_demoData <- target_demoData[1:100, ]
  > pData(target_demoData)[["slide"]] <- 
  +     factor(pData(target_demoData)[["slide name"]])
  > protocolData(target_demoData)[["pool_rep"]] <- 
  +     factor(protocolData(target_demoData)[["pool_rep"]])
  > mixedOutmc <- mixedModelDE(target_demoData,
  +                            elt = "exprs_norm",
  +                            modelFormula = ~ pool_rep +  (1 | slide),
  +                            groupVar = "pool_rep",
  +                            nCores = 12,
  +                            multiCore = TRUE,
  +                            pAdjust = NULL
  + )
  Error in .check_ncores(cores) : 12 simultaneous processes spawned
  Calls: mixedModelDE -> <Anonymous> -> .check_ncores
  Execution halted

> checking tests ...
  See below...

> checking for unstated dependencies in examples ... OK
   WARNING
  ‘qpdf’ is needed for checks on size reduction of PDFs

> checking installed package size ... NOTE
    installed size is 25.3Mb
    sub-directories of 1Mb or more:
      doc       5.3Mb
      extdata  19.1Mb

> checking DESCRIPTION meta-information ... NOTE
  License components which are templates and need '+ file LICENSE':
    MIT

> checking top-level files ... NOTE
  File
    LICENSE
  is not mentioned in the DESCRIPTION file.

> checking R code for possible problems ... NOTE
  aggregateCounts: no visible binding for global variable ‘TargetName’
  hkNorm: no visible binding for global variable ‘TargetName’
  mixedModelDE: multiple local function definitions for ‘deFunc’ with
    different formal arguments
  setGrubbsFlags: no visible binding for global variable ‘TargetName’
  setGrubbsFlags : <anonymous>: no visible binding for global variable
    ‘Module’
  setProbeRatioFlags: no visible binding for global variable ‘TargetName’
  setTargetFlags: no visible global function definition for ‘analtye’
  subtractBackground : <anonymous>: no visible binding for global
    variable ‘Module’
  setSignatureFuncs<-,NanoStringGeoMxSet-character: no visible global
    function definition for ‘setSigFuncs<-’
  signatureScores,NanoStringGeoMxSet: no visible global function
    definition for ‘assayDataElement2’
  signatureScores,NanoStringGeoMxSet: no visible global function
    definition for ‘.sigCalc’
  Undefined global functions or variables:
    .sigCalc Module TargetName analtye assayDataElement2 setSigFuncs<-

2022-04-08 23:42 UTC, NicoleEO requested changes
Last few

2022-04-11 14:46 UTC, maddygriz commented on tests/testthat/test_coercions.R
> +    expect_true(all(seurat_object[[]][,colnames(seurat_object[[]]) %in%
strangely enough yes, that is one of Seurat's accessor functions

2022-04-11 18:44 UTC, NicoleEO approved these changes
looks great!

2022-04-11 22:11 UTC, merged