Update object
Nanostring-Biostats/GeomxTools pull request #155
Opened 2022-04-12 20:34 UTC by maddygriz

the nsclc object in the coercion vignette is too old to test this update but works with datasets from v2.0.
When we address #141 we can change the dataset to use this function or just update it to v2.2

2022-04-12 20:59 UTC, maddygriz commented
resolves #155

2022-04-12 23:05 UTC, NicoleEO requested changes

2022-04-12 23:05 UTC, NicoleEO commented on R/NanoStringGeoMxSet-class.R
> +setMethod("updateObject", signature = "NanoStringGeoMxSet",
Add roxygen comments or add to man page. Also, add importFrom BiocGenerics updateObject

2022-04-12 23:05 UTC, NicoleEO commented on vignettes/GeomxSet_coercions.Rmd
> +data.frame(nsclc@assayData$exprs[seq_len(5), seq_len(5)])
Use accessor

2022-04-12 23:05 UTC, NicoleEO commented on vignettes/GeomxSet_coercions.Rmd
> +data.frame(nsclc@assayData$exprs[seq_len(5), seq_len(5)])
Use accessor

2022-04-12 23:05 UTC, NicoleEO commented on vignettes/GeomxSet_coercions.Rmd
> +nsclc@analyte <- "RNA"
Did you mean to updateObject(nsclc) here?

2022-04-12 23:05 UTC, NicoleEO commented on vignettes/GeomxSet_coercions.Rmd
> +nsclc@analyte <- "RNA"
Did you mean to updateObject(nsclc) here?

2022-04-13 01:51 UTC, maddygriz commented on vignettes/GeomxSet_coercions.Rmd
> +nsclc@analyte <- "RNA"
Nope. nsclc is a patch job of a geomxset object (that isn't technically valid for the last version) so it breaks the updateObject for reasons unrelated to this update. We really need to address it in it's own package which is where #141 comes into play but I don't think we need to do it for this release.

2022-04-13 16:10 UTC, NicoleEO approved these changes

2022-04-13 16:32 UTC, merged