add multipanel norm
Nanostring-Biostats/GeomxTools pull request #90
Opened 2021-07-22 15:50 UTC by rvitancol

Need to bump the version if merging to dev.

2021-07-26 21:20 UTC, NicoleEO requested changes

2021-07-26 21:20 UTC, NicoleEO commented on R/NanoStringGeoMxSet-normalize.R
> +    pools <- as.list(unique(fData(object)[["Module"]]))
I notice this is quite different from the plugin neg norm. That one should be optimized for time and I'm pretty sure it works with single panel as well. I don't think you need to split. I would just replace 65-112 with the neg norm plugin logic altogether. Let me know if you need help or if I am wrong and this doesn't work with single panel.

2021-07-26 21:20 UTC, NicoleEO commented on tests/testthat/test_normalization.R
> +if (length(unique(fData(target_demoData)[["Module"]]) > 1)){
Remove if since we know it is >1 in the test

2021-07-26 21:20 UTC, NicoleEO commented on tests/testthat/test_normalization.R
> +if (length(unique(fData(target_demoData)[["Module"]]) > 1)){
remove if here too

2021-07-27 19:58 UTC, rvitancol commented on R/NanoStringGeoMxSet-normalize.R
> +    pools <- as.list(unique(fData(object)[["Module"]]))
@NicoleEO Please check. I updated these. It seems that the lines moved so there are a lot of changes. But I only updated lines 65 to 112

2021-07-27 20:12 UTC, rvitancol commented on tests/testthat/test_normalization.R
> +if (length(unique(fData(target_demoData)[["Module"]]) > 1)){
done

2021-07-27 20:12 UTC, rvitancol commented on tests/testthat/test_normalization.R
> +if (length(unique(fData(target_demoData)[["Module"]]) > 1)){
done

2021-07-27 22:20 UTC, merged